version: '3'
services:

  zoo1:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zoo1
    hostname: zoo1
    logging:
      driver: local
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888;144.22.48.184:2888:3888
    networks:
      - kafka

  kafka1:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka1
    logging:
      driver: local
    ports:
      - "9093:9093"
      - "29101:29101"
    depends_on:
      - zoo1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,144.22.48.184:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://144.22.52.73:9093,INTERNAL://kafka1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      EXTRA_ARGS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.0.jar=29101:/usr/share/jmx_exporter/kafka-broker.yaml
    networks:
      - kafka
    volumes:
      - ./jmx-exporter:/usr/share/jmx_exporter/
      - kafka-jmx-volume:/jmx-exporter

  kafka2:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka2
    logging:
      driver: local
    ports:
      - "9094:9094"
      - "29102:29102"
    depends_on:
      - zoo1
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,144.22.48.184:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS:  EXTERNAL://144.22.52.73:9094,INTERNAL://kafka2:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      EXTRA_ARGS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.0.jar=29102:/usr/share/jmx_exporter/kafka-broker.yaml
    networks:
      - kafka
    volumes:
      - ./jmx-exporter:/usr/share/jmx_exporter/
      - kafka-jmx-volume:/jmx-exporter
    
  kafka3:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka3
    logging:
      driver: local
    ports:
      - "9095:9095"
      - "29103:29103"
    depends_on:
      - zoo1
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,144.22.48.184:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS:  EXTERNAL://144.22.52.73:9095,INTERNAL://kafka3:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      EXTRA_ARGS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.0.jar=29103:/usr/share/jmx_exporter/kafka-broker.yaml
    networks:
      - kafka
    volumes:
      - ./jmx-exporter:/usr/share/jmx_exporter/
      - kafka-jmx-volume:/jmx-exporter


  prometheus:
    image: prom/prometheus:v2.10.0
    container_name: prometheus
    logging:
      driver: local
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-volume:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - kafka
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    logging:
      driver: local
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - kafka
    environment:
      - "GF_SECURITY_ADMIN_USER=kafka"
      - "GF_SECURITY_ADMIN_PASSWORD=kafka"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    ports:
      - 3000:3000
volumes:
  kafka-jmx-volume:
  grafana-volume:
  prometheus-volume:
networks:
  kafka:
    external: false
