version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    hostname: zoo2
    networks:
     - kafka-net
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=144.22.52.73:2888:3888;2181 server.2=zoo2:2888:3888;2181

  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    container_name: kafka2
    networks:
     - kafka-net
    ports:
     - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://144.22.48.184:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      KAFKA_ZOOKEEPER_CONNECT: 144.22.52.73:2181,zoo2:2181
      KAFKA_ADVERTISED_HOST_NAME: 144.22.48.184
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     
     
networks:
  kafka-net:
    external: true